theme: minima
title: About Sarthak Jain
author: Sarthak Jain
email: Sjain2@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Sarthak Jain! I am a junior at East Brunswick
  High School. Some of my hobbies include: soccer, coding, reading,
  videogames, basketball, etc. I hope you like my website!

# social links
instagram_username: sarthakjainnn # DO NOT include the @ character, or else the build will fail!
twitter_username:  Sarthak07216505 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
